<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMEW4tB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMEW4tB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMEW4tB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMEW4tB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMEW4tB\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMEW4tB',
    'container.build_id' => '9aa24036',
    'container.build_time' => 1597665527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMEW4tB');
